openapi: 3.2.0
info:
  title: Hyperlabs.Web Tech API
  version: '1.0'
servers:
- url: /api
tags:
- name: Tech
paths:
  /v1/tech/is-alive:
    get:
      tags:
      - Tech
      responses:
        '204':
          description: No Content
components:
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
