openapi: 3.2.0
info:
  title: Hyperlabs.Web Customer Profile API
  version: '1.0'
servers:
- url: /api
tags:
- name: CustomerProfile
paths:
  /v1/profile:
    get:
      tags:
      - CustomerProfile
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Customers.ProfileDto'
            application/json:
              schema:
                $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Customers.ProfileDto'
            text/json:
              schema:
                $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Customers.ProfileDto'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
      security:
      - oauth2: []
    put:
      tags:
      - CustomerProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Customers.ChangeProfileDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Customers.ChangeProfileDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Customers.ChangeProfileDto'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
      security:
      - oauth2: []
components:
  schemas:
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      title: ProblemDetails
      type: object
      properties:
        type:
          title: String
          type:
          - string
          - 'null'
        title:
          title: String
          type:
          - string
          - 'null'
        status:
          title: Nullable`1
          type:
          - integer
          - 'null'
          format: int32
        detail:
          title: String
          type:
          - string
          - 'null'
        instance:
          title: String
          type:
          - string
          - 'null'
      additionalProperties:
        title: Object
    Hyperlabs.Web.Areas.Customer.Models.Customers.ChangeProfileDto:
      title: ChangeProfileDto
      type: object
      properties:
        firstName:
          title: String
          type:
          - string
          - 'null'
        lastName:
          title: String
          type:
          - string
          - 'null'
        phoneNumber:
          title: String
          type:
          - string
          - 'null'
        country:
          title: String
          type:
          - string
          - 'null'
        state:
          title: String
          type:
          - string
          - 'null'
        address:
          title: String
          type:
          - string
          - 'null'
        company:
          title: String
          type:
          - string
          - 'null'
        inquiryType:
          title: String
          type:
          - string
          - 'null'
      additionalProperties: false
    Hyperlabs.Web.Areas.Customer.Models.Customers.ProfileDto:
      title: ProfileDto
      type: object
      properties:
        firstName:
          title: String
          type:
          - string
          - 'null'
        lastName:
          title: String
          type:
          - string
          - 'null'
        phoneNumber:
          title: String
          type:
          - string
          - 'null'
        country:
          title: String
          type:
          - string
          - 'null'
        state:
          title: String
          type:
          - string
          - 'null'
        address:
          title: String
          type:
          - string
          - 'null'
        company:
          title: String
          type:
          - string
          - 'null'
        inquiryType:
          title: String
          type:
          - string
          - 'null'
        email:
          title: String
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
