openapi: 3.2.0
info:
  title: Hyperlabs.Web Admin Website Featured Products API
  version: '1.0'
servers:
- url: /api
tags:
- name: AdminWebsiteFeaturedProducts
paths:
  /v1/admin/website/featured-products:
    get:
      tags:
      - AdminWebsiteFeaturedProducts
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
    post:
      tags:
      - AdminWebsiteFeaturedProducts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.CreateWebsiteFeaturedProductDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.CreateWebsiteFeaturedProductDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.CreateWebsiteFeaturedProductDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
  /v1/admin/website/featured-products/{id}:
    put:
      tags:
      - AdminWebsiteFeaturedProducts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFeaturedProductDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFeaturedProductDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFeaturedProductDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
  /v1/admin/website/featured-products/{id}/move:
    post:
      tags:
      - AdminWebsiteFeaturedProducts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
components:
  schemas:
    Hyperlabs.Domain.Products.Models.ProductAttributeTypeCode:
      title: ProductAttributeTypeCode
      enum:
      - 1
      - 2
      type: integer
      format: int32
    Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFeaturedProductDto:
      title: ChangeWebsiteFeaturedProductDto
      type: object
      properties:
        productAttributeTypeCode:
          $ref: '#/components/schemas/Hyperlabs.Domain.Products.Models.ProductAttributeTypeCode'
      additionalProperties: false
    Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto:
      title: MoveDto
      type: object
      properties:
        delta:
          title: Int32
          type: integer
          format: int32
      additionalProperties: false
    Hyperlabs.Web.Areas.Admin.Models.Website.CreateWebsiteFeaturedProductDto:
      title: CreateWebsiteFeaturedProductDto
      type: object
      properties:
        productId:
          title: Guid
          type: string
          format: uuid
        productAttributeTypeCode:
          $ref: '#/components/schemas/Hyperlabs.Domain.Products.Models.ProductAttributeTypeCode'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
