openapi: 3.2.0
info:
  title: Hyperlabs.Web Admin Website Faq API
  version: '1.0'
servers:
- url: /api
tags:
- name: AdminWebsiteFaq
paths:
  /v1/admin/website/faqs:
    get:
      tags:
      - AdminWebsiteFaq
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Get admin website faqs
      x-summary-source: derived
      operationId: getV1AdminWebsiteFaqs
      x-operation-id-source: derived
    post:
      tags:
      - AdminWebsiteFaq
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Create admin website faqs
      x-summary-source: derived
      operationId: postV1AdminWebsiteFaqs
      x-operation-id-source: derived
  /v1/admin/website/faqs/{id}:
    get:
      tags:
      - AdminWebsiteFaq
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Get admin website faqs by id
      x-summary-source: derived
      operationId: getV1AdminWebsiteFaqsById
      x-operation-id-source: derived
    put:
      tags:
      - AdminWebsiteFaq
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Replace admin website faqs by id
      x-summary-source: derived
      operationId: putV1AdminWebsiteFaqsById
      x-operation-id-source: derived
    delete:
      tags:
      - AdminWebsiteFaq
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Delete admin website faqs by id
      x-summary-source: derived
      operationId: deleteV1AdminWebsiteFaqsById
      x-operation-id-source: derived
  /v1/admin/website/faqs/{id}/move:
    post:
      tags:
      - AdminWebsiteFaq
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Create admin website faqs by id move
      x-summary-source: derived
      operationId: postV1AdminWebsiteFaqsByIdMove
      x-operation-id-source: derived
components:
  schemas:
    Hyperlabs.Web.Areas.Admin.Models.Shared.MoveDto:
      title: MoveDto
      type: object
      properties:
        delta:
          title: Int32
          type: integer
          format: int32
      additionalProperties: false
    Hyperlabs.Web.Areas.Admin.Models.Website.ChangeWebsiteFaqDto:
      title: ChangeWebsiteFaqDto
      type: object
      properties:
        question:
          title: String
          type:
          - string
          - 'null'
        answer:
          title: String
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
