openapi: 3.2.0
info:
  title: Hyperlabs.Web Product Units API
  version: '1.0'
servers:
- url: /api
tags:
- name: Product Units
paths:
  /v1/admin/products/{productId}/units:
    get:
      tags:
      - Product Units
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Get admin products by product id units
      x-summary-source: derived
      operationId: getV1AdminProductsByProductIdUnits
      x-operation-id-source: derived
    post:
      tags:
      - Product Units
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Create admin products by product id units
      x-summary-source: derived
      operationId: postV1AdminProductsByProductIdUnits
      x-operation-id-source: derived
  /v1/admin/units/{id}:
    put:
      tags:
      - Product Units
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Replace admin units by id
      x-summary-source: derived
      operationId: putV1AdminUnitsById
      x-operation-id-source: derived
    delete:
      tags:
      - Product Units
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Delete admin units by id
      x-summary-source: derived
      operationId: deleteV1AdminUnitsById
      x-operation-id-source: derived
  /v1/admin/products/{productId}/units/generate:
    post:
      tags:
      - Product Units
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
      summary: Create admin products by product id units generate
      x-summary-source: derived
      operationId: postV1AdminProductsByProductIdUnitsGenerate
      x-operation-id-source: derived
components:
  schemas:
    Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitDto:
      title: ChangeProductUnitDto
      type: object
      properties:
        name:
          title: String
          type:
          - string
          - 'null'
        variables:
          title: ChangeProductUnitVariableDto[]
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitVariableDto'
      additionalProperties: false
    Hyperlabs.Web.Areas.Admin.Models.ProductUnits.ChangeProductUnitVariableDto:
      title: ChangeProductUnitVariableDto
      type: object
      properties:
        variableId:
          title: Guid
          type: string
          format: uuid
        valueId:
          title: Guid
          type: string
          format: uuid
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
