openapi: 3.2.0
info:
  title: Hyperlabs.Web Roles API
  version: '1.0'
servers:
- url: /api
tags:
- name: Roles
paths:
  /v1/admin/roles:
    get:
      tags:
      - Roles
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
components:
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
