openapi: 3.2.0
info:
  title: Hyperlabs.Web Website Representatives API
  version: '1.0'
servers:
- url: /api
tags:
- name: WebsiteRepresentatives
paths:
  /v1/website/representatives/us:
    get:
      tags:
      - WebsiteRepresentatives
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                title: IEnumerable`1
                type: array
                items:
                  $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto'
            application/json:
              schema:
                title: IEnumerable`1
                type: array
                items:
                  $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto'
            text/json:
              schema:
                title: IEnumerable`1
                type: array
                items:
                  $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto'
  /v1/website/representatives/international:
    get:
      tags:
      - WebsiteRepresentatives
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                title: IEnumerable`1
                type: array
                items:
                  $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto'
            application/json:
              schema:
                title: IEnumerable`1
                type: array
                items:
                  $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto'
            text/json:
              schema:
                title: IEnumerable`1
                type: array
                items:
                  $ref: '#/components/schemas/Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto'
components:
  schemas:
    Hyperlabs.Web.Areas.Customer.Models.Website.WebsiteRepresentativeDto:
      title: WebsiteRepresentativeDto
      type: object
      properties:
        name:
          title: String
          type:
          - string
          - 'null'
        link:
          title: String
          type:
          - string
          - 'null'
        isOther:
          title: Boolean
          type: boolean
        phones:
          title: String[]
          type:
          - array
          - 'null'
          items:
            title: String
            type: string
        emails:
          title: String[]
          type:
          - array
          - 'null'
          items:
            title: String
            type: string
        workingTime:
          title: String
          type:
          - string
          - 'null'
        territories:
          title: String[]
          type:
          - array
          - 'null'
          items:
            title: String
            type: string
        mapColor:
          title: String
          type:
          - string
          - 'null'
        title:
          title: String
          type:
          - string
          - 'null'
        order:
          title: Int32
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
