openapi: 3.2.0
info:
  title: Hyperlabs.Web Website Banner API
  version: '1.0'
servers:
- url: /api
tags:
- name: WebsiteBanner
paths:
  /v1/website/banner:
    get:
      tags:
      - WebsiteBanner
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
