openapi: 3.2.0
info:
  title: Hyperlabs.Web Website Featured Products API
  version: '1.0'
servers:
- url: /api
tags:
- name: WebsiteFeaturedProducts
paths:
  /v1/website/featured-products:
    get:
      tags:
      - WebsiteFeaturedProducts
      responses:
        '200':
          description: OK
      summary: Get website featured products
      x-summary-source: derived
      operationId: getV1WebsiteFeaturedProducts
      x-operation-id-source: derived
components:
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
