openapi: 3.2.0
info:
  title: Hyperlabs.Web Variable Types API
  version: '1.0'
servers:
- url: /api
tags:
- name: VariableTypes
paths:
  /v1/admin/variable-types:
    get:
      tags:
      - VariableTypes
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
    post:
      tags:
      - VariableTypes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
  /v1/admin/variable-types/{id}:
    put:
      tags:
      - VariableTypes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto'
          text/json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
    delete:
      tags:
      - VariableTypes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          title: Guid
          type: string
          format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
      - oauth2: []
components:
  schemas:
    Hyperlabs.Web.Areas.Admin.Models.VariableTypes.ChangeVariableTypeDto:
      title: ChangeVariableTypeDto
      type: object
      properties:
        name:
          title: String
          type:
          - string
          - 'null'
        values:
          title: ICollection`1
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Hyperlabs.Web.Areas.Admin.Models.VariableTypes.VariableTypeValueDto'
      additionalProperties: false
    Hyperlabs.Web.Areas.Admin.Models.VariableTypes.VariableTypeValueDto:
      title: VariableTypeValueDto
      type: object
      properties:
        id:
          title: Nullable`1
          type:
          - string
          - 'null'
          format: uuid
        value:
          title: String
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: apiKey
      description: 'Standard Authorization header using the Bearer scheme. Example: "Bearer {token}"'
      name: Authorization
      in: header
